replicaCount: 5

image:
  repository: siddharth67/php-random-shapes:v1
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80
  targetPort: 80
  
color:
   circle: orange
   oval: purple
   triangle: brown
   rectangle: pink
   square: blue
